#include <sstream>
#include <sys/uio.h>
#include <math.h>
#include <cmath>
#include <cstring>
#include <iostream>
#include <string>
#include <unistd.h>
#include <vector>
#include <unordered_map>
#include <chrono>
#include <thread>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/extensions/XTest.h>
#include <unordered_map>
#include <random>
#include <fstream>
#include <sys/stat.h>
#include <algorithm>
#include <cctype>
#include <locale>
#include <iterator>
#include "ConfigLoader.cpp"
#include "Offsets.cpp"
#include "WeaponId.cpp"
#include "Util.cpp"
#include "FloatVector2D.cpp"
#include "FloatVector3D.cpp"
#include "GlowMode.cpp"
#include "Color.cpp"
#include "Memory.cpp" 
#include "XDisplay.cpp"
#include "Level.cpp"
#include "LocalPlayer.cpp"
#include "Player.cpp"
#include "Sense.cpp"
#include "TriggerBot.cpp"
#include "AimBot.cpp"
#include "NoRecoil.cpp"
